### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by shurub3l** [toopay/bootstrap-markdown#111]
Create a NuGet package for bootstrap-markdown, for easier installation and updates.

**Comment by toopay** [comment]
There is already one [here](https://www.nuget.org/packages/bootstrap-markdown.less/). Don't know who maintain it, but i think as long its available, it should satisfy this issue

**Comment by shurub3l** [comment]
As you can see my comment was posted on Oct 14, 2014, and the NuGet package was uploaded on October 28 2014. :)

**Comment by toopay** [comment]
Yep. Sorry for very late reply.

**Comment by mikeschuld** [comment]
Some changes to jQuery 2.2 are not working with the 2.7 version that the NuGet package supplies.

Can you please update the available version on NuGet to a more recent release.

**Comment by toopay** [comment]
@mikeschuld Sorry, i'm not the maintainer of that package. I guess you can contact him via email?
