### ISSUE TITLE
No fullscreen when editor is inside a modal

### ISSUE THREAD

**Issue by luisafonsocarvalho** [toopay/bootstrap-markdown#133]
If the editor is placed inside a bootstrap modal, the fulscreen doesn't open successfully.

**Comment by kjeske** [comment]
+1

**Comment by divad** [comment]
+1

**Comment by abreksa4** [comment]
+1

**Comment by ykoryakov** [comment]
+1

**Comment by jeromemiranda** [comment]
+1

**Comment by lodev09** [comment]
Okay I'm afraid there is no "official" fix for this within the plugin. The `.modal-dialog` is containing the `.md-editor.md-fullscreen-mode ` block. If only css has a "parent selector" then this would be much easier :(

However, `onFullscreen` and `onFullscreenExit` events are the workaround to fix this issue. Modify `modal-dialog` css via js on the fly. `onFullscreen` event, turn it into:
```
.modal-dialog {
  width: 100%;
  height: 100%;
  margin: 0;
}
```
then remove them on fullscreen end
