### ISSUE TITLE
Display Tables Properly

### ISSUE THREAD

**Issue by emilepetrone** [toopay/bootstrap-markdown#148]
Tables don't seem to display properly. Example:

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

**Comment by lodev09** [comment]
`bootstrap-markdown` does not handle the format of the result markup, you need to follow the API from your parser (e.g. [markdown-js](https://github.com/evilstreak/markdown-js)) on customizing result or submit an issue in their plugin site.
