### ISSUE TITLE
Add support to upload images to cloudinary

### ISSUE THREAD

**Issue by cadwmaster** [toopay/bootstrap-markdown#149]
That would give the option of attach images easily (upload to cloudinary), now you need to have the image already in the web and get the url to paste.

**Comment by lodev09** [comment]
You can do this using the existing `onShow` event callback. See here: http://embed.plnkr.co/atyuBnVNktl8YSfdfPJT/preview

Just go over with the code on how I implemented it inside the event callback. :)

**Comment by lodev09** [comment]
I just checked and actually, I did not put the code in the `onShow` event (that was an old code). But anyway, you will see what I mean regarding uploading images and pasting it to the `textarea` of the editor. I'm using [filedrop](https://github.com/weixiyen/jquery-filedrop) plugin

**Comment by cadwmaster** [comment]
Thanks, actually I found that I can create additional buttons with my own functionality so I extended to support cloudinary. Nice plugin, was really easy to extend.

Cheers!!

**Comment by lodev09** [comment]
Good for you mate :+1:
