### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by vkshrivastva** [toopay/bootstrap-markdown#150]
Bootstrap Datepicker and Bootstrap Markdown is not working together.

When using the datepicker and markdown together Markdown is not working.

Thanks,
Vikash

**Comment by acrobat** [comment]
@vkshrivastva can you provide a jsfiddle example showing the problem? Also which datepicker you use?

**Comment by vkshrivastva** [comment]
I got it solved.

Thanks,
Vikash
