### ISSUE TITLE
Displaying data from the database

### ISSUE THREAD

**Issue by majimboo** [toopay/bootstrap-markdown#151]
After using the editor to enter data, how about displaying the data without showing the editor? How would one do that?

**Comment by lodev09** [comment]
I think there is an option to let you initialize the plugin on `preview` mode

**Comment by acrobat** [comment]
Yes indeed there is an initialstate option added in [#64](https://github.com/toopay/bootstrap-markdown/pull/64/files#diff-b51abdc7b330b3d26a0925cef67cd3e9R737) 

Possible values: initialstate: 'editor' or 'preview'

**Comment by lodev09** [comment]
@acrobat thanks for pointing that out :)

**Comment by majimboo** [comment]
Aah, can I ask for a example usage? Thanks.

**Comment by acrobat** [comment]
@majimboo here is [an example](http://jsfiddle.net/vmcwxrLt/) ;)

**Comment by majimboo** [comment]
@acrobat , cheers, oddly it still shows the editor. I just want to display something from the database. :D

**Comment by acrobat** [comment]
Hmm then I don't understand your question.. This option opens the editor with the preview mode default enabled (you can also disable the other actions) this way the editor is just a preview screen

**Comment by lodev09** [comment]
If you are concerned about the editor "layout" then you should use your markdown parser (not this plugin) to just parse the string and put it in a `div`

**Comment by majimboo** [comment]
Actually, I have markdown data in the database. That was saved using this library. Now, I want to display that data to the user. Ofcourse I do not want the user to edit the data, nor do I want to show the editor. I just want to show the HTML of the markdown.

**Comment by lodev09** [comment]
@majimboo see my comment above

Additionally, if you want to have an option to edit the `div` content, then you can use this plugin. see more example here: http://www.codingdrama.com/bootstrap-markdown/

**Comment by majimboo** [comment]
Yah, I did that problem now is this plugin is saving new lines as special characters and markdownjs seems to expect `\n` for new lines. So now all my parsed markdown has no line breaks.
