### ISSUE TITLE
Preview Not Working?

### ISSUE THREAD

**Issue by ptsx** [toopay/bootstrap-markdown#162]
Hi,

Preview not working? Why is that?

Thanks.

`$("textarea[data-provide=markdown]").markdown({language:'tr'});`

![screenshot from 2015-03-19 01 01 04](https://cloud.githubusercontent.com/assets/10997360/6721252/d5e9e9e2-cdd3-11e4-9b84-15abe648de14.png)
![screenshot from 2015-03-19 01 00 48](https://cloud.githubusercontent.com/assets/10997360/6721253/d5ed81c4-cdd3-11e4-9b11-b8d1460e39c0.png)

**Comment by acrobat** [comment]
did you include a markdown parser lib? See note at the bottom of the page http://www.codingdrama.com/bootstrap-markdown/

> NOTE
>Altought the primary purpose of this plugin is to provide Markdown editor, the design is allowing the plugin to be used as a general purpose editor.
>The preview functionalities and html to markdown conversion are provided by 3rd party codes : markdown-js, marked (default failover if markdown-js lib not available) and to-markdown. Without them, this plugin would still work and convert the content as-is, so you could easily modify those functionalities yourself via available hooks.

**Comment by RufusJWB** [comment]
I have the same problem: It is working with markdown.js but not with marked.js .

**Comment by tchoulihan** [comment]
This should be on the front page. I had to dig to find this.

**Comment by enlivenapp** [comment]
I agree it should be mentioned.  Been digging for 30 minutes as to why the preview button wasn't working.

**Comment by tankywoo** [comment]
+1, The **NOTE** should be put on the head of the page 😢
