### ISSUE TITLE
Wrong size after preview in fullscreen

### ISSUE THREAD

**Issue by freetonik** [toopay/bootstrap-markdown#165]
Hi guys,
found a bug:

1. Switch to fullscreen mode
2. Press 'Preview'
3. Switch back from fullscreen mode (without disabling preview).

Result looks like this: ![bug](http://i.imgur.com/n5cDOXy.png)

**Comment by PlugIN73** [comment]
Oh, yea! I saw it, too! :+1:

**Comment by xserrat** [comment]
Hi,

I would ask about this issue because I'm having the same problem and changes are in my code..

Thanks!
