### ISSUE TITLE
Editor should honor bootstrap styling

### ISSUE THREAD

**Issue by dasjestyr** [toopay/bootstrap-markdown#179]
For instance, the text area that I am using for the editor has the form-control style applied to it but bootstrap-markdown seems to override it; removing the textarea padding and rounded corners etc... The text area also seems to grow beyond the column width of the form.

**Comment by toopay** [comment]
There is a .less file included in the package, so you could generate your own style. See : https://github.com/toopay/bootstrap-markdown/blob/master/less/bootstrap-markdown.less
