### ISSUE TITLE
Add link with mailto:and https:

### ISSUE THREAD

**Issue by dornstein** [toopay/bootstrap-markdown#180]
Is there a reason the add link button is coded to only support http?  You can't put in mailto: or https: links.  This seems like a problem (and it for my users).

Seems like one line of (problematic) code:

```javascript
       if (link !== null && link !== '' && link !== 'http://' && link.substr(0,4) === 'http') {
```

Am I missing something?  Can this get improved?

**Comment by microcipcip** [comment]
Yes please, it should also allow realtive links.

**Comment by toopay** [comment]
@dornstein PR? :)

**Comment by dornstein** [comment]
Yeah, fair enough.  For the moment I just had to pull out the third and fourth clauses in the check above, but I'll try to get you a PR...
