### ISSUE TITLE
Hide all button

### ISSUE THREAD

**Issue by dungphanxuan** [toopay/bootstrap-markdown#183]
Hello, i want to hide all button, and only show textarea. so what option to config!
thank

**Comment by toopay** [comment]
I dont get it. You should just use textarea?

**Comment by jasonpolites** [comment]
I want to do the same thing.  The idea is to allow the use of markdown syntax with the preview feature, and default to rendering the formatted version, but not add the UI for the toolbar itself.  Basically what gihub does *right here* in this issue editor.

**Comment by AlissonRS** [comment]
As far as I've read the source code from **bootstrap-markdown.js**, this can be achieved by passing "all" as parameter, like this:
```javascript
    $("#your-editor").markdown({
        onShow: function (e) {
            e.hideButtons("all");
        }
    })
```

**Comment by jacoborus** [comment]
@AlissonRS I'm not interested at all in this feature

**Comment by AlissonRS** [comment]
@jacoborus Oh, I just marked the wrong person, I'm sorry, I'm gonna edit my post.

**Comment by jacoborus** [comment]
:+1:
