### ISSUE TITLE
Is compatible without Boostrap?

### ISSUE THREAD

**Issue by Master-Antonio** [toopay/bootstrap-markdown#194]
Hello.
Is compatible without bootstrap?
Can you create version without bootstrap?

**Comment by acrobat** [comment]
The library has a "hard" dependency on bootstrap, so without their css it won't render correctly. We could ship an extra standalone css file to use the editor without bootstrap (but keep the bootstrap style). Feel free to send a PR for that!

[eternicode/bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker/tree/master/dist/css) delivers twbs 2 & 3 stylesheets and standalone stylesheets for a twbs 2 & 3 look

**Comment by Master-Antonio** [comment]
Yes. Will be fantastic.
Is because i use Materializecss , bootstrap go in conflict with materialize.
