### ISSUE TITLE
cannot find module 'bootstrap-markdown'

### ISSUE THREAD

**Issue by promethe42** [toopay/bootstrap-markdown#196]
Hello,

I've added `"bootstrap-markdown": "latest"` to my `package.json` and I've added a `require('bootstrap-markdown');` in my code, but when I build with browserify I get the following error:

```
Error: Cannot find module 'bootstrap-markdown' from '/vagrant/www/app/script/page'
```

I'm using tons of other npm packages and that's the only error I get.

Please advise.

Regards,

**Comment by acrobat** [comment]
Bootstrap-markdown is currently only a jquery plugin, but i will make a PR soon to make it also available to be included with requirejs

**Comment by mabasic** [comment]
+1

**Comment by promethe42** [comment]
I'm sorry but I don't understand how the merged pull request has anything to do with the issue here (which AFAIK still exists in 2.10.0 by the way).

As far as I can tell, the pull request adds requirejs support to load jquery from bootstrap markdown. But it doesn't make bootstrap-markdown work by using require('bootstrap-mardkown'). At least the code in my original post still doesn't work and gives the exact same error.

I think this issue should be re-opened.

**Comment by driesvints** [comment]
I was also still stumbling into this and apparently `require('bootstrap-markdown/js/bootstrap-markdown');` does the trick.
