### ISSUE TITLE
Directly format when text is selected

### ISSUE THREAD

**Issue by AugierLe42e** [toopay/bootstrap-markdown#202]
Currently, bootstrap-markdown insert a a new piece of text when a formatting button is clicked. It would be nice if it could directly format a piece of text when selected.

**Comment by toopay** [comment]
I'm not entirely sure with your suggestion, can you elaborate more?

**Comment by AugierLe42e** [comment]
For instance, when I write `this is a text` inside the editor, select it and click on emphasis button, the selected text will be erased ans replaced by `**`. The idea would be to format the selected text rather than erase it so that `this is a text` will be replaced byt `*this is a text*`.

**Comment by acrobat** [comment]
Which version of the plugin do you use? And in which browser do you experience this behavior? I can't reproduce this with the latest version of the bootstrap-markdown plugin

**Comment by AugierLe42e** [comment]
Hmm... Can't reproduce now. Must have been solved somewhere in a verison. Thanks !
