### ISSUE TITLE
this.$textarea.on(...).on(...).on is not a function

### ISSUE THREAD

**Issue by canfiax** [toopay/bootstrap-markdown#215]
I am getting the following error:

    this.$textarea.on(...).on(...).on is not a function

![image](https://cloud.githubusercontent.com/assets/3786627/12249049/b1105716-b8bd-11e5-99ac-86a522b7f2c3.png)

![image](https://cloud.githubusercontent.com/assets/3786627/12249044/ac0a0b72-b8bd-11e5-91d3-48841724ed3b.png)

It used to work fine 10 minutes ago. I did not make any changes to this.

**Comment by acrobat** [comment]
Can you provide a jsfiddle with a working example of the error?

**Comment by garlian** [comment]
Same here!

**Comment by acrobat** [comment]
Issue caused by jquery/jquery#2812, fixed should be pushed to 1.12.1/2.2.1 other jquery version will work!

**Comment by mgol** [comment]
Note, though, that passing an `undefined` handler is not supported and never has. We plan to fix it for 2.2.1 because it's inconsistent with how 1.12.0 works and we want both versions to be as close to each other as possible. This will most likely just start throwing in jQuery 3.0.0 (we'll have a beta out soon). If you disagree with this, please comment on #2812.

**Comment by acrobat** [comment]
@mgol Can you explain a bit more what is wrong with this piece of code? I don't understand what you mean!

**Comment by mgol** [comment]
@acrobat `elem.on(eventName, null or undefined)` is not and has never been supported. See https://api.jquery.com/on/, there is no such signature in the docs.

**Comment by mgol** [comment]
And I assume this piece of code doesn't work because `this.keypress` is undefined and so is `$.proxy(this.keypress, this)`.

**Comment by canfiax** [comment]
How do we overcome this issue? Bootstrap 4 alpha depends on jQuery 1.9.1 - 2

**Comment by acrobat** [comment]
@mgol thanks for the info! I will push a fix to this library!

**Comment by acrobat** [comment]
[bootstrap-markdown 2.10.0](https://github.com/toopay/bootstrap-markdown/releases/tag/v2.10.0) was released with a fix for this issue!
