### ISSUE TITLE
*jquery* and *bootstrap-markdown* Preview/Exit full screen buttons unresponsiveness

### ISSUE THREAD

**Issue by Martii** [toopay/bootstrap-markdown#216]
So I [updated jQuery about a day ago](https://github.com/OpenUserJs/OpenUserJS.org/pull/869/files) and didn't notice until tonight that [the Preview button and exit full screen mode](https://github.com/OpenUserJs/OpenUserJS.org/pull/873) was failing in this package.

I'm not sure whether to create the issue with this project or [jQuery](https://github.com/jquery/jquery)'s ... but I thought I would start here first.

The work-around is to back out the jQuery update from 2.2.0 back to 2.1.0 but was hoping for some more insight here.

TIA 
OUJS Admin

**Comment by acrobat** [comment]
Hi @Martii, can you provide an jsfiddle example? So we can test this bug!

**Comment by Martii** [comment]
Not until next week although I don't use jsfiddle ever so perhaps a little demo project to see what appears. I notice this project doesn't have any tests otherwise I would have run that first... although you are welcome to check out the dev commit that showed this and see it for yourself. ;) e.g. `$ git checkout adf1f88` [of OUJS](https://github.com/OpenUserJs/OpenUserJS.org)... I can temporarily restore it to production too but coordinating with you might be a trick. :)

I should mention I only tested this issue on SM before I reverted... `Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 SeaMonkey/2.39` but in a few days I can do the git checkout under Fx, Chromium and a few others to see if it's isolated to SM... which is unlikely since it's Moz's backend.

There are a number of open issues on jQuery's repo too and some breaking changes there... so who knows for sure what's going on.

**Comment by Martii** [comment]
btw here's some Error Console clips:

``` sh-session

Warning: ReferenceError: reference to undefined property this[r]
Source File: http://localhost:8080/redist/npm/jquery/dist/jquery.js
Line: 2

Warning: ReferenceError: reference to undefined property p.toggle
Source File: http://localhost:8080/redist/npm/bootstrap-markdown/js/bootstrap-markdown.js
Line: 1

Warning: ReferenceError: reference to undefined property this.keypress
Source File: http://localhost:8080/redist/npm/bootstrap-markdown/js/bootstrap-markdown.js
Line: 1

Warning: ReferenceError: reference to undefined property u.disabled
Source File: http://localhost:8080/redist/npm/jquery/dist/jquery.js
Line: 2

Warning: ReferenceError: reference to undefined property t.uniqueID
Source File: http://localhost:8080/redist/npm/jquery/dist/jquery.js
Line: 1

Warning: ReferenceError: reference to undefined property oe.event.triggered
Source File: http://localhost:8080/redist/npm/jquery/dist/jquery.js
Line: 2

Warning: ReferenceError: reference to undefined property n.closest(...)[0]
Source File: http://localhost:8080/redist/npm/bootstrap-markdown/js/bootstrap-markdown.js
Line: 1



Error: TypeError: this.$textarea.on(...).on(...).on is not a function
Source File: http://localhost:8080/redist/npm/bootstrap-markdown/js/bootstrap-markdown.js
Line: 1
```

this looks a lot like toopay/bootstrap-markdown#215

**Comment by acrobat** [comment]
I've created a jsfiddle with jquery 2.2 which can reproduce the bug: http://jsfiddle.net/4prknn7m/1/

Bug doesn't appear with jquery 2.1.*

**Comment by acrobat** [comment]
Bug can be related to jquery/jquery#2812. Will investigate this issue further later today

**Comment by mgol** [comment]
Note, though, that passing an `undefined` handler is not supported and never has. We plan to fix it for 2.2.1 because it's inconsistent with how 1.12.0 works and we want both versions to be as close to each other as possible. This will most likely just start throwing in jQuery 3.0.0 (we'll have a beta out soon). If you disagree with this, please comment on #2812.

**Comment by Martii** [comment]
Closing as a duplicate as I'm following toopay/bootstrap-markdown#215 now since it appears to be that... easier to follow one issue.

**Comment by acrobat** [comment]
[bootstrap-markdown 2.10.0](https://github.com/toopay/bootstrap-markdown/releases/tag/v2.10.0) was released with a fix for this issue!

**Comment by Martii** [comment]
Awesome... I'll give it a shot tomorrow when I'm back at dev station. TIA.

**Comment by acrobat** [comment]
Ah yes indeed @Martii!

Ping @toopay can you publish the latest version on npm?
