### ISSUE TITLE
Remove Predefined buttons

### ISSUE THREAD

**Issue by jackmarketon** [toopay/bootstrap-markdown#23]
Hey, I wasn't able to find it if it exists, but it would be awesome to be able to remove the predefined buttons.

Disabling and hiding via css is stupid, but that's what I'm doing atm.

**Comment by danneu** [comment]
How do you override the default buttons (e.g. initialize with none of them) when
the library is using a recursive merge (passing `true` as first argument to
`$.extend`)?

    var defaults = { buttons: [{ foo: 'bar' }] };

    // Recursive merge

    $.extend(true, {}, defaults, { buttons: [] })  
    //=> { buttons: [{ foo: 'bar' }] }
    $.extend(true, {}, defaults, { buttons: [{ baz: 42 }] })  
    //=> { buttons: [{ foo: 'bar', baz: 42 }] }

    // Shallow merge

    $.extend({}, defaults, { buttons: [] })  
    //=> { buttons: [] }

https://github.com/toopay/bootstrap-markdown/blob/51b48d8249803e62ae543ba29cb3dcb8f8de5cbb/js/bootstrap-markdown.js#L45

**Comment by toopay** [comment]
@danneu What i refer as overide is off-course :
```
var defaults = { buttons: [{ foo: 'bar' }] };
$.extend(true, {}, defaults, { buttons: [{ foo: 'baz' ] })  
// => { buttons: [{ foo: 'baz }] }
```
Bear in mind that `options` contains other callbacks as well, so `deep` flag is turned on intentionally.

**Comment by danneu** [comment]
@toopay 

I use bootstrap-markdown as a BBCode editor (no Markdown at all). So I needed to initialize bootstrap-markdown with none of its default buttons. Instead, I implemented my own buttons including a Preview button.

I patched my local copy of bootstrap-markdown from this:

    $.extend(true, {}, defaults, ...

to this:

    $.extend({}, defaults, ...

That lets me do this:

    $('#editor').markdown({
      buttons: [[]],  // Clear the default buttons
      additionalButtons: [ ... ]  // Supply my own buttons
    });

If I want to just modify the default buttons, then I can do the deep merge myself:

    $('#editor').markdown({
      buttons: $.extend(true, {}, $.markdown.defaults.buttons, [ { name: 'my-bold' } ])
    });

**Comment by toopay** [comment]
Glad you could use this plugin to suit your needs. I may refactor those part to allow less-hacky integration to other parser (BBCode, etc). Thanks for the input.

**Comment by danneu** [comment]
Cool.

As I improve my bootstrap-markdown BBCode hacks, I would like to share my work. Perhaps one day you can change "bootstrap-markdown" to "bootstrap-editor with optional Markdown and BBCode plugins". :)
