### ISSUE TITLE
underscore '_' character not showing

### ISSUE THREAD

**Issue by yonetmen** [toopay/bootstrap-markdown#248]
underscore '_' characters not showing. If you use only one underscore then it works just fine but when you use more than one underscores (i use them in URLs) then it doesn't show those characters and I get false url address.

**Comment by yonetmen** [comment]
Why do we need to use escape '\' character with use of '_' characters? What is special about them?

**Comment by acrobat** [comment]
Which markdown processor do you use? I think it's a problem of the processor (marked, markdown-js,...) as _ is the delimiter of italics text

**Comment by yonetmen** [comment]
Oh, I see... I am fairly new to Markdown. I use "markdown.js". Sorry if this was not a real issue as I thought.

**Comment by acrobat** [comment]
No problem! I would suggest opening an issue at the [markdown-js repository](https://github.com/evilstreak/markdown-js) so they can explain if it's a bug or if you should escape those characters
