### ISSUE TITLE
Numbered lists do not correctly add the next number for next list item

### ISSUE THREAD

**Issue by webdevbrian** [toopay/bootstrap-markdown#256]
Here's a pen from another person who submitted another issue for a test: http://codepen.io/greenido/pen/BKomNv

If you type "list" as an example multiple times with a line break, then select the numbered list option, it just adds "1." to each of them, not correctly going to 2,3,4, etc.

Here's a screencast of the bug for clarification: http://d.pr/v/cPO6

The desired outcome should be shown as:

```
1. List
2. List
3. List
```
etc.

**Comment by webdevbrian** [comment]
I added a PR to fix this here: https://github.com/toopay/bootstrap-markdown/pull/257

**Comment by toopay** [comment]
@webdevbrian Appreciated!
