### ISSUE TITLE
How to hide fullscreen button

### ISSUE THREAD

**Issue by manuelcalerosolis** [toopay/bootstrap-markdown#265]
Please can you help to hide the fullscreen button?

Thanks

**Comment by lodev09** [comment]
Try the `fullscreen` option. Something like this:
```
$('#textarea').markdown({
    // ...
    fullscreen: { enabled: false }
    // ...
});
```

See [documentation](http://www.codingdrama.com/bootstrap-markdown/)

**Comment by manuelcalerosolis** [comment]
$('#textarea').markdown({
    // ...
    fullscreen: { enable: false }
    // ...
});


See documentation.

**Comment by lodev09** [comment]
wrong paste... lol
