### ISSUE TITLE
New Line not work

### ISSUE THREAD

**Issue by Cosmagnaccio** [toopay/bootstrap-markdown#272]
Hi in bootstrap markdown new line inside paragraph not work.
![immagine](https://cloud.githubusercontent.com/assets/12465297/21293751/69646d6c-c52d-11e6-9509-24bc512163d8.png)

Instead if i put two spaces after the new line i have the correct result...
![immagine](https://cloud.githubusercontent.com/assets/12465297/21293762/bc3ca806-c52d-11e6-9024-efd7da263060.png)
why this strange behavior??

Has anyone found a solution?Thanks :)

**Comment by lodev09** [comment]
It's your parser's issue i.e. if you're using [marked](https://github.com/chjj/marked), you need to report this to them.
This is specified in the notes section in the documentation:
> The preview functionalities and html to markdown conversion are provided by 3rd party codes : markdown-js, marked (default failover if markdown-js lib not available) and to-markdown. Without them, this plugin would still work and convert the content as-is, so you could easily modify those functionalities yourself via available hooks.
