### ISSUE TITLE
How to access the content?

### ISSUE THREAD

**Issue by frozflame** [toopay/bootstrap-markdown#28]
Green on JavaScript...

As you provided at the bottom of [this page](http://toopay.github.io/bootstrap-markdown/), I assume I can only use the APIs by passing a call back function to  

```
$('#some-div-or-textarea').markdown({ 
    ...
    , callback: function(e){
        ...
        e.getContent();
}})
```

But how can I get the `e` outside the `markdown({})`?
What I want is to send the modified text to the server.
Any help?

**Comment by mthhk** [comment]
it dos't work
