### ISSUE TITLE
Headers & Hashtags

### ISSUE THREAD

**Issue by githubjeka** [toopay/bootstrap-markdown#280]
[Correct Syntax Header](http://daringfireball.net/projects/markdown/syntax#header)

to string `#my-hash-tag` bootstrap-markdown generate header tag. It's wrong.

For example correct behavior you can see here on GitHub

`#my-hash-tag`
#my-hash-tag

`# my-hash-tag`
# my-hash-tag

**Comment by raviatif18** [comment]
# hash-tag

**Comment by raviatif18** [comment]
kj

**Comment by lodev09** [comment]
this is your parser's issue.
