### ISSUE TITLE
the code is not format for preview

### ISSUE THREAD

**Issue by heyx-any** [toopay/bootstrap-markdown#284]
I write some java code,but markdown editor is not format the code,
input code:
```
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
```
But got the following results：
![20170705214118](https://user-images.githubusercontent.com/28948897/27866986-ed944f28-61ca-11e7-9f96-cafd312ea962.png)

**Comment by lodev09** [comment]
this is something related to external plugins that are used I would guess -- haven't encountered any issue with code preview on my end.
