### ISSUE TITLE
Is it possible to have a toolbar icon for a bulleted list?

### ISSUE THREAD

**Issue by ajtruckle** [toopay/bootstrap-markdown#291]
Thanks.

**Comment by acrobat** [comment]
This is covered by the docs. See the "editor panel - additionalButtons" section. http://www.codingdrama.com/bootstrap-markdown/

**Comment by ajtruckle** [comment]
Thank you. But from what I can tell this is going to create a group after the preview button? I don’t want that. I want the bullet button next to the other two list style buttons.

Andrew

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
