### ISSUE TITLE
Hiding editor but not edited content

### ISSUE THREAD

**Issue by ctzurcanu** [toopay/bootstrap-markdown#30]
I think this is a very common usecase:

when we have:

```
<div data-provide="markdown-editable">
          <h3>This is some editable heading</h3>
          <p>Well, actually all contents within this "markdown-editable" context is really editable. Just click anywhere!</p>
</div>
```

we want ability to show the editor on click and hide just the editor (not the edited content) on blur

**Comment by andrejbranch** [comment]
I agree with @ctzurcanu that it should be easier to toggle the editor. And I dont think onblur event can help you default to hiding the editor.

In my use case I have a comment system that I would like to allow markdown usage. So by default I would like to only show the parsed content ( the html ), and if user clicks edit then show the editor.

It doesn't seem like there is an easy way to do this
