### ISSUE TITLE
make a javascript implementation?

### ISSUE THREAD

**Issue by dbursem** [toopay/bootstrap-markdown#309]
This project is labeled "javascript" but it's actually completely written in jQuery. With jQuery becoming more and more obsolete, it would be nice to have an actual javascript implementation.

Otherwise please consider changing the label to jQuery or at least mention the dependency, might save some people like me from disappointment.

**Comment by lodev09** [comment]
it's bootstrap-markdown and bootstrap requires jquery. anyone that uses bootstrap knows that it uses jquery so I don't see any issues at all.

PS: jquery is a framework of javascript - still a javascript

**Comment by lodev09** [comment]
btw, this plugin does not even have it's own native parser i.e. it uses supported 3rd party library parser like `marked`. I think you're looking for something like that as this library is mainly for UI.

You can actually easily make something similar with this plugin without using jquery or even bootstrap and by just using `marked` + `textarea`, no need to use a fancy plugin like this if you don't like jquery. 😄
