### ISSUE TITLE
Support FontAwesome 5

### ISSUE THREAD

**Issue by GregJohnStewart** [toopay/bootstrap-markdown#315]
Currently, when using FontAwesome 5, and setting up the markdown to use font awesome, some of the items simply don't appear. This is due to there being changes to FontAwesome 5 that are sometimes not backwards compatible. I notice that there is backwards compatibility already set up for 3, I would recommend a similar approach to supporting FA5.

I could implement most of the change myself (I already have locally in my project) and submit a pull request, it isn't that complicated and I already know how FA 5 works, but I don't want to step on any toes if you guys are already working on it.

**Comment by NicolasCARPi** [comment]
While waiting for the maintainers of this project to sort out this issue, I made a fontawesome compatible fork : https://www.npmjs.com/package/bootstrap-markdown-fa5

**Comment by niknokseyer** [comment]
You can submit a pull request @GregJohnStewart and @NicolasCARPi.

**Comment by lodev09** [comment]
just modify the `$.fn.markdown.defaults.buttons` object and add a `fa-5` configuration or something.

Pull request is welcome too.

**Comment by royduin** [comment]
I've created a PR for this: https://github.com/toopay/bootstrap-markdown/pull/320
