### ISSUE TITLE
preview not work.

### ISSUE THREAD

**Issue by farshidrezaei** [toopay/bootstrap-markdown#316]
when i click on preview button, just show me markdown code.
exp:
`##Farshid`
result should be **Farshid** but just show me `##Farshid`.
how can i fix it?

**Comment by edoferiyus** [comment]
I think you need to include http://www.codingdrama.com/bootstrap-markdown/js/markdown.js on your code

**Comment by kaushikindianic** [comment]
I try to use bootstrap-markdown with web pack.
install with node.
```npm i bootstrap-markdown
```
How can I setup dependent  markdown.js  and to-markdown.js?
