### ISSUE TITLE
Markdown Editable with Links

### ISSUE THREAD

**Issue by niknokseyer** [toopay/bootstrap-markdown#318]
Is there a way on Editable Markdown (`data-provide="markdown-editable"`) to make links (e.g. www.example.com) clickable instead of switching it to the editor right away?

**Comment by lodev09** [comment]
@niknokseyer you can manually initiate/create the editor when a link/button is clicked:
```
$('#my_button').on('click', function() {
  $('#texarea').markdown();
});
```
