### ISSUE TITLE
bootstrap 4 version?

### ISSUE THREAD

**Issue by rob-lindman** [toopay/bootstrap-markdown#319]
what it says, yo. 

I plopped this into a page with bs4 and it works, but the glyphicons aren't compatible, so the editor just doesn't show any icons. 

this takes away my happy thought.

**Comment by ericfri** [comment]
Set the icon library to 'fa'

**Comment by rob-lindman** [comment]
A little detail on that would be useful.

**Comment by JRawly** [comment]
http://www.codingdrama.com/bootstrap-markdown/

Look at the usage section.
Essentially, add 'iconlibrary': 'fa' to your initialisation code, or data-iconlibrary="fa" to your data attributes depending on your method of integration.

**Comment by rob-lindman** [comment]
thanks for the info.
