### ISSUE TITLE
Demo & Documentation Link in README.md is dead

### ISSUE THREAD

**Issue by cgatesman** [toopay/bootstrap-markdown#324]
404 - http://toopay.github.io/bootstrap-markdown/

**Comment by ellepereira** [comment]
this might help: https://web.archive.org/web/20170514034153/http://www.codingdrama.com:80/bootstrap-markdown

**Comment by toopay** [comment]
Sorry guys, this has been fixed. New CNAME has been added, and it now lives at http://www.taufanaditya.com/bootstrap-markdown/
