### ISSUE TITLE
Allow line breaks

### ISSUE THREAD

**Issue by ulisessp** [toopay/bootstrap-markdown#63]
I know I can 'force' a line break by ending a line with two or more spaces and then a return, but, Is there any way to treat returns as br's and keep paragraphs separated by a blank line?

**Comment by spikeitservices** [comment]
tdrhsrtghrstfhgfhfdhghdghdgfhtredytertyrtyertyertyrtyreytyrttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt
