### ISSUE TITLE
Glyphicons do not display

### ISSUE THREAD

**Issue by hacktorious** [toopay/bootstrap-markdown#66]
I've attempted setting up bootstrap-markdown in sinatra/haml from both the tar and zip files.  Neither seems to work.  The buttons do not display.  

Bootstrap 3.1.1
toopay-bootstrap-markdown-v2.4.0-0-g16dfaa8.tar

HAML:
%html
  %head
    %script{:type=>'text/javascript', :src=>"/js/bootstrap-markdown.js"}
    %script{:type=>'text/javascript', :src=>"https://github.com/evilstreak/markdown-js"}
    %script{:type=>'text/javascript', :src=>"https://github.com/chjj/marked"}
    %link(rel="stylesheet" type="text/css" href="/css/bootstrap-markdown.min.css")
  %body
    %form
      %input{type: 'textarea', 'data-provide' => 'markdown', rows: 10, name: 'content' }

**Comment by AttitudeMonger** [comment]
Hey, can you tell me how do I accomplish this in Bootstrap markdown: show a popup outside with 10 different glyphicons, and clicking on any of them renders that icon in the markdown text area?
