### ISSUE TITLE
Unclear on how to hide the markdown editor

### ISSUE THREAD

**Issue by coderhs** [toopay/bootstrap-markdown#94]
Hey there, I wish to make the markdown editor show/hidden on button click.

To make it visible i  wrote the following code with in the click trigger

```
$("#article").markdown({autofocus:true,savable:false,iconlibrary:'fa'});
```

but when i try to use the `$('#article').showEditor()` toggle api. it gives the following error

`TypeError: Object [object Object] has no method 'showEditor'`.

**Comment by niknokseyer** [comment]
Thanks @lodev09. That's helpful.
